######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 13 09:59:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
SQLITE_PATH=/usr/local
DEPENDPATH += $$SQLITE_PATH/include
INCLUDEPATH += $$SQLITE_PATH/include
LIBS += -L$$SQLITE_PATH/lib
LIBS += -lsqlite3

# Input
HEADERS += EditRecord.h managementform.h
FORMS += management.ui
SOURCES += EditRecord.cpp main.cpp managementform.cpp
TRANSLATIONS += qr_zh.ts
